version: "3.8"

services:
  backend:
    build: ./server
    container_name: patrol_backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

  frontend:
    build: ./client
    container_name: patrol_frontend
    ports:
      - "80:80"
    depends_on:
      - backend